## Reference Links - Deep Learning Programming Frameworks

* **Intro to Google Colab, free GPU and TPU for Deep Learning (Episode 1) -** https://www.youtube.com/watch?v=vVe648dJOdI

* **Introduction to Tensorflow & Keras for Deep Learning with Python (3.2) -** https://www.youtube.com/watch?v=PsE73jk55cE

* **Introduction to Tensorflow and Keras -** https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_03_2_keras.ipynb

* **TensorFlow Tutorial -** https://www.tensorflow.org/tutorials

* **Visualise the derivative of a function here -** https://www.mathsisfun.com/calculus/derivative-plotter.html

* **TensorFlow 2.0 Introduction -** https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true

# <center> Tensorflow Basics

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## TensorFlow Fundamentals
As per the TensorFlow website, TensorFlow is "an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications."

Learning to work with tensorflow comes handy in developing ML and DL models and in this notebooks we will quickly have a look at the fundamentals/basics of tensorflow. Note that a very detailed understanding of TensorFlow are not required for this course and we will cover some very basic concepts here. You can go ahead and explore this [site](https://www.tensorflow.org/) if you are further interested.

## Basic operations with TensorFlow

In [2]:
#?tf.square

In [3]:
a = 4 + 2j #complex number
b = 6 + 7j

print('a:',a,"b:",b,'\n')

print(a-b,'\n')
print(a*b,'\n')

c = a + b

print(c,'\n')

d = tf.square(c)
print(d,'\n')

a: (4+2j) b: (6+7j) 

(-2-5j) 

(10+40j) 

(10+9j) 

tf.Tensor((19+180j), shape=(), dtype=complex128) 



## Tensors
As we Know, tensors are array of numbers arranged in space. We can call a vector(1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. Below, find out how to create a [constant](https://www.tensorflow.org/api_docs/python/tf/constant) tensor:






In [4]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print("Elements :\n",c)

Elements :
 tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


* You can get its value as a Numpy array by calling `.numpy()`:

In [5]:
import numpy as np
y = np.array([[1, 2, 2], [8, 2, 5]])
print(y)
# We can also convert a tensor into a numpy array by using .numpy()
c.numpy()

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

We can get the dimensions and the datatype of the a tf.tensor as demonstrated below - 

In [6]:
print('Tensor Data Type', c.dtype)
print("Tensor Dimension :",c.ndim)
print('Tensor Shape', c.shape)
# You can notice the similarity with numpy 
# You can also call the different default tensors as you would do for numpy

Tensor Data Type <dtype: 'float32'>
Tensor Dimension : 2
Tensor Shape (2, 3)


### Find a detailed reference to creating different tensors:


1.   [Converting python/numpy objects to tensors](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)
2.   [Generating random values from a normal distribution](https://www.tensorflow.org/api_docs/python/tf/random/normal)
3.   [Converting tensor values to strings ](https://www.tensorflow.org/api_docs/python/tf/strings/as_string)
4.   [Createing a tensor of ones](https://www.tensorflow.org/api_docs/python/tf/ones)
5.   [Creating a tensor of zeroes](https://www.tensorflow.org/api_docs/python/tf/zeros)
6.   [TensorFlow for maths](https://www.tensorflow.org/api_docs/python/tf/math)





----------------

### [Variables](https://www.tensorflow.org/guide/variable) with tf.Variable()

A tensorflow Variable is a tensor that is used to store value that can later be updated. You need to initialize a variable with some value at the time of creation.A tensorflow Variable is a tensor that is used to store value that can later be updated. You need to initialize a variable with some value at the time of creation.

In [7]:
random_variable = tf.ones(shape=(3,3))

print(type(random_variable))
print(random_variable,'\n')


#random variable
tf_variable = tf.Variable(random_variable)
print(type(tf_variable))
print(tf_variable,'\n')

#you can also update the values of your variable.
tf_variable.assign(tf.zeros(shape = (3,3)))
print(tf_variable)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) 

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)> 

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


* You can find more on updating a variable [here](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add).

-------

## GradientTapeGradientTape : 
Now we learn about the <b>[`GradientTape`](https://www.tensorflow.org/api_docs/python/tf/GradientTape)</b> which is used to record operations for automatic differentiation.

* TensorFlow Tutorial 6- GradientTape in TensorFlow - https://www.youtube.com/watch?v=tDG52BjkGUY

In [8]:
# computing derivative for the function 3x^2 at x = 3

x = tf.constant(3.0) #gradient at

with tf.GradientTape() as g:
    g.watch(x) #record the operations
    y = 3* x**2
dy_dx = g.gradient(y, x) 
print(dy_dx)

tf.Tensor(18.0, shape=(), dtype=float32)


In [9]:
# We can also use nested GradientTape() for the second derivative
#computing second derivative for the function 4x^3 at x = 4.0

x = tf.constant(4.0)
with tf.GradientTape() as gt:
    gt.watch(x)
    with tf.GradientTape() as g:
        g.watch(x)  
        y = 4* x**3
    dy_dx = g.gradient(y, x)
d2y_dx2 = gt.gradient(dy_dx,x)
print(d2y_dx2)

tf.Tensor(96.0, shape=(), dtype=float32)


# <center> Practice Questions

#### 1. Create a constant tensor array 'x' like [2,3,4] and find element wise e^x.  Refer to the website [here](https://www.tensorflow.org/api_docs/python/tf/math/exp).



In [10]:
#your code here


#### 2. Declare a variable with a 3*2 shaped floating elements array with elements picked from a random normal distributions.   

In [11]:
#your code here


#### 3. Subtract 1 from every element of the above matrix.


In [12]:
#your code here


#### 4. Calculate the third derivative of the function 4x^3 + x^2 + 1 at x = 1

In [13]:
#your code here
x = tf.constant(1.0) 

#### 5. Calculate dot product of matrices [[1,2,3],[4,5,6],[7,8,9]] and [[1],[2],[3]] using tensorflow functions. Also, find the element wise multiplication of the two.

In [14]:
#your code here for dot product
a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
b = tf.constant([[1],[2],[3]])

In [15]:
# your code here for element wise product
